language: cpp
dist: trusty
compiler: g++
os: linux
sudo: required
addons: &gcc5
  apt:
    packages:
      - g++-5
      - gcc-5
    sources:
      - ubuntu-toolchain-r-test
before_script:
script: make